config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

BugzillaMirror::Application.routes.draw do
  mount Sidekiq::Web, at: "/sidekiq"

  resources :dashboard do
    collection do
      get 'index'
      get 'reload_issues'
      get 'update_issues'
    end
  end

  resources :errata_reports do
    collection do
      get 'index'
    end
  end

  resources :statistics_reports do
    collection do
      get 'index'
    end
  end

  root :to => 'dashboard#index'
  get '/dashboard/view_issue(/:id)'         => 'dashboard#view_issue'
  get '/dashboard/refresh_issue(/:id)'      => 'dashboard#refresh_issue'

  get '/issues(.:format)'                   => 'issues#show',   :format => 'json'
  get '/issues(/:id)(.:format)'             => 'issues#show',   :format => 'json'
  get '/issues(/:action(/:id))(.:format)'   => 'issues#show',   :format => 'json'
  match '/issues(/:id)(.:format)'           => 'issues#update', :format => 'json', :via => [:post]
  match '/issues(/:action(/:id))(.:format)' => 'issues#update', :format => 'json', :via => [:post]

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  protect_from_forgery
  #
  # Bugzilla Mirror Web Interface (Html)
  #
  def index
    @selected_filter = params['selected_filter'] || @selected_filter || "None"
    @selected_owner  = params['selected_owner']  || @selected_owner  || "All"
    @selected_status = params['selected_status'] || @selected_status || ["ON_DEV"]
    @issues = Issue.order(sort_column + " " + sort_direction)

    selected_sqlfilter = filter_name_to_sqlfilter(@selected_filter)
    @issues = @issues.where(selected_sqlfilter)               if selected_sqlfilter

    @issues = @issues.where(:assigned_to => @selected_owner)  if @selected_owner  != "All"
    @issues = @issues.where(:status      => @selected_status) if @selected_status != ["All"]

    @issues_updated_at = Issue.order("updated_at ASC").last.nil? ? "None Found" :
      Issue.order("updated_at ASC").last.updated_at

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def reload_issues
    WorkerManager.reload_database_from_bugzilla
  end

  def update_issues
    WorkerManager.update_database_from_bugzilla
  end

  def view_issue
    @bug_id = params['id']
    @issue  = Issue.where(:bug_id => @bug_id).first
  end

  def refresh_issue
    @bug_id = params['id']
    WorkerManager.update_issues_from_bugzilla([@bug_id])
    view_issue
    render :action => 'view_issue'
  end
end

app/views/dashboard/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bug_id %><br />
    <%= f.text_field :bug_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :assigned_to %><br />
    <%= f.text_field :assigned_to %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :flag_version %><br />
    <%= f.text_field :flag_version %>
  </div>
  <div class="field">
    <%= f.label :version_ack %><br />
    <%= f.text_field :version_ack %>
  </div>
  <div class="field">
    <%= f.label :pm_ack %><br />
    <%= f.text_field :pm_ack %>
  </div>
  <div class="field">
    <%= f.label :devel_ack %><br />
    <%= f.text_field :devel_ack %>
  </div>
  <div class="field">
    <%= f.label :qa_ack %><br />
    <%= f.text_field :qa_ack %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboard/index.html.erb
<h1>Bugzilla Mirror Dashboard</h1>
<% unless BugzillaConfig.get_config(:product).blank? %>
  <table>
    <tr>
      <td><b>Product:</b></td>
      <td> <%= BugzillaConfig.get_config(:product) %> </td>
      <td><b>Last Updated On:</b></td>
      <td> <%= BugzillaConfig.fetch_synctime %></td>
      <td><b>Updated From:</b></td>
      <td> <%= BugzillaConfig.get_config(:uri) %></td>
    </tr>
  </table>
<% end %>
<hr>
<table>
  <tr>
  <%= form_tag(statistics_reports_path, method: "get") do %>
    <%= submit_tag('Statistics Report', :title => 'Run the Statistics Report') %>
  <% end %>
  <%= form_tag("/dashboard/update_issues", method: "get") do %>
    <%= submit_tag('Update Issues', :title => 'Load updated issues from Bugzilla') %>
  <% end %>
  <%= form_tag("/sidekiq", method: "get") do %>
    <%= submit_tag('SideKiq Dashboard', :title => 'View the SideKiq Dashboard for Queued Request') %>
  <% end %>
  <%= form_tag("/dashboard", method: "get") do %>
    <%= submit_tag('Reload Dashboard', :title => 'Reload this Dashboard with default filters') %>
  <% end %>
  </tr>
</table>

<hr>
<br />
<%= form_tag(errata_reports_path, method: "get") do %>
  <%= label_tag(:q, "Select Flag Version:") %>
  <%= select_tag(:flag_version, options_for_select(available_flag_versions)) %>
  <%= submit_tag('Errata Report', :title => 'Run the Errata Report against the selected Version') %>
<% end %>

<hr>
<h3>Select Dashboard Filters:</h3>
<table>
  <tr>
    <%= form_tag("/dashboard", method: "get") do %>
      <%= label_tag(:q, "Status:") %>
      <%= select_tag(:selected_status, options_for_select(available_issue_states, @selected_status), :multiple => true) %>
      &nbsp; &nbsp; &nbsp; &nbsp;
      <%= label_tag(:q, "Owner:") %>
      <%= select_tag(:selected_owner, options_for_select(available_issue_assigned_to, @selected_owner)) %>
      &nbsp; &nbsp;
      <%= label_tag(:q, "Filter:") %>
      <%= select_tag(:selected_filter, options_for_select(available_filters, @selected_filter)) %>
      &nbsp; &nbsp;
      <%= submit_tag('Apply Filters') %>
    <% end %>
  </tr>
</table>

<hr>
<br>
<h2>Issue Table</h2>

<p>
  <b>Last Updated:</b>
  <%= @issues_updated_at %>
</p>
<p>
<table>
  <tr>
  <i>Number of Issues Shown: </i><b> <%= @issues.count %> </b> &nbsp; &nbsp;
  <i>Total Number of Issues: </i><b> <%= Issue.count %> </b>
  </tr>
</p>

<table>
  <tr>
    <th align="left"><%= sortable "bug_id", "Bug Id" %></th>
    <th align="left"><%= sortable "status" %></th>
    <th align="left"><%= sortable "assigned_to", "Assignee" %></th>
    <th align="left">Summary</th>
    <th align="left"><%= sortable "flags" %></th>
  </tr>

<%
  @issues.each do |issue| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td><%= form_tag("/dashboard/view_issue/#{issue.bug_id}", method: "get") do %>
          <%= submit_tag(issue.bug_id) %>
        <% end %>
    </td>
    <td><%= issue.status      %></td>
    <td><%= issue.assigned_to %></td>
    <td><%= issue.summary     %></td>
    <td><%= issue.flags       %></td>
  </tr>
<% end %>
</table>

<br />

app/views/dashboard/reload_issues.html.erb
<p id="notice"><%= notice %></p>

<p>
<b> Request to Reload All Issues from Bugzilla has been submitted</b>
</p> 

<br/>
<%= form_tag("/sidekiq", method: "get") do %>
  <%= submit_tag('View the SideKiq Dashboard for Queued Request') %>
<% end %>

<%= link_to 'Back', dashboard_index_path %>

app/views/dashboard/update_issues.html.erb
<p id="notice"><%= notice %></p>

<p>
<b> Request to Update Issues from Bugzilla has been submitted </b>
</p> 

<br/>
<%= form_tag("/sidekiq", method: "get") do %>
  <%= submit_tag('View the SideKiq Dashboard for Queued Request') %>
<% end %>

<%= link_to 'Back', dashboard_index_path %>

app/views/dashboard/view_issue.html.erb
<p id="View Issue <%= @bug_id %>"></p>
<p><b>Bug Id:</b> <%= @bug_id %> - <b><%= @issue.summary %></b></p>
<table>
  <tr>
    <td align="right"><b>Status:</b></td>
    <td><%= @issue.status %></td>
  </tr>
  <tr>
    <td align="right"><b>Assigned To:</b></td>
    <td><%= @issue.assigned_to %></td>
  </tr>
  <tr>
    <td align="right"><b>Last updated at:</b></td>
    <td><%= @issue.updated_at %></td>
  </tr>
</table>
<br>
<table>
  <tr>
    <%= form_tag("/dashboard", method: "get") do %>
      <%= submit_tag("Dashboard") %>
    <% end %>
    <%= form_tag("/dashboard/view_issue/#{@bug_id}", method: "get") do %>
      <%= submit_tag("Refresh View") %>
    <% end %>
    <%= form_tag("/dashboard/refresh_issue/#{@bug_id}", method: "get") do %>
      <%= submit_tag("Reload Issue from Bugzilla") %>
    <% end %>
    &nbsp; &nbsp; &nbsp; &nbsp;
    &lt;<%= link_to "View in Bugzilla", url_to_bugzilla(@bug_id) %>&gt;
  </tr>
</table>


<p>
  <table border="2">
    <% Issue::ATTRIBUTES.sort.each do |attr|
        unless %w(bug_id).include?(attr) %>
          <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
            <td><i><%= attr %></i></td>
            <td><% if attr == :flags %>
              <table border="1">
              <% @issue.flag_hash.sort.each do |k, v| %>
                <tr>
                  <td><b><%= k %></b></td>
                  <td><b><%= v %></b></td>
                </tr>
              <% end %>
              </table>
             <% else %>
                <%= @issue.send(attr) %>
            <% end %>
            </td>
          </tr>
      <% end
    end %>
    <tr><td><i>Dependent Issues</i></td>
        <td><% @issue.dependents.each do |relation| %>
            <%= form_tag("/dashboard/view_issue/#{relation.bug_id}", method: "get") do %>
              <%= submit_tag(relation.bug_id) %> <%= flag_hash_versions(relation.flag_hash) %> - <%= relation.summary %>
      <% end
    end %></td></tr>
    <tr><td><i>Blocked Issues</i></td><td><% @issue.blocked_issues.each do |relation| %>
      <%= form_tag("/dashboard/view_issue/#{relation.bug_id}", method: "get") do %>
        <%= submit_tag(relation.bug_id) %> <%= flag_hash_versions(relation.flag_hash) %> - <%= relation.summary %>
      <% end
    end %></td></tr>
    <tr><td><i>Duplicate Issues</i></td><td><% @issue.duplicates.each do |relation| %>
      <%= form_tag("/dashboard/view_issue/#{relation.bug_id}", method: "get") do %>
        <%= submit_tag(relation.bug_id) %> <%= flag_hash_versions(relation.flag_hash) %> - <%= relation.summary %>
      <% end
    end %></td></tr>
    <tr><td><i>Clone Of</i></td><td><% @issue.cloned_from.each do |relation| %>
      <%= form_tag("/dashboard/view_issue/#{relation.bug_id}", method: "get") do %>
        <%= submit_tag(relation.bug_id) %> <%= flag_hash_versions(relation.flag_hash) %> - <%= relation.summary %>
      <% end
    end %></td></tr>
    <tr><td><i>Cloned Issues</i></td><td><% @issue.clones.each do |relation| %>
      <%= form_tag("/dashboard/view_issue/#{relation.bug_id}", method: "get") do %>
        <%= submit_tag(relation.bug_id) %> <%= flag_hash_versions(relation.flag_hash) %>
      <% end
    end %></td></tr>
    <tr><td><i>Comments</i></td> </tr>
    <% @issue.comments.order("count ASC").each do |comment| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td align="right" style="white-space: nowrap"><% if comment.count == 0 %>
           <i>Description</i><% else %> #<%= comment.count %>
        <% end %>
        <br><%= comment.created_by %>
        <br><%= comment.created_on %>
        <br><% if comment.private? %>
              <b><i>Private</i></b>
        <% end %>
        </td>
        <td><pre><%= comment.text %></pre></td></tr>
    <% end %>
    </tr>
  </table>
</p>

<%= link_to 'Back', dashboard_index_path %>