config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

BugzillaMirror::Application.routes.draw do
  mount Sidekiq::Web, at: "/sidekiq"

  resources :dashboard do
    collection do
      get 'index'
      get 'reload_issues'
      get 'update_issues'
    end
  end

  resources :errata_reports do
    collection do
      get 'index'
    end
  end

  resources :statistics_reports do
    collection do
      get 'index'
    end
  end

  root :to => 'dashboard#index'
  get '/dashboard/view_issue(/:id)'         => 'dashboard#view_issue'
  get '/dashboard/refresh_issue(/:id)'      => 'dashboard#refresh_issue'

  get '/issues(.:format)'                   => 'issues#show',   :format => 'json'
  get '/issues(/:id)(.:format)'             => 'issues#show',   :format => 'json'
  get '/issues(/:action(/:id))(.:format)'   => 'issues#show',   :format => 'json'
  match '/issues(/:id)(.:format)'           => 'issues#update', :format => 'json', :via => [:post]
  match '/issues(/:action(/:id))(.:format)' => 'issues#update', :format => 'json', :via => [:post]

end

app/controllers/errata_reports_controller.rb
class ErrataReportsController < ApplicationController
  # GET /errata_reports
  # GET /errata_reports.json
  def index
    @need_acks = []
    @have_acks = []

    # TODO: When where.not method becomes available in Rails 4 this
    #       logic could possibly be simplified.

    Issue.where(:status => "POST").order("#{sort_column} #{sort_direction}").each do |bz|
      if display_flag_version?(bz, params["flag_version"])
        entry = BugEntry.new(bz)

        if entry.all_acks?
          @have_acks << entry
        else
          @need_acks << entry
        end
      end
    end

    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end

  private

  def display_flag_version?(bz, requested_flag_version)
    requested_flag_version == "All" || get_flag_versions(bz.flag_hash).include?(requested_flag_version)
  end
end

app/views/errata_reports/index.erb
<p id="notice"><%= notice %></p>

<p>
  <b>BZs That Need ACK(s):</b></br>
  <u><i>Legend:</i></u></br>
  <b>-</b> : Have ACK For This Column</br>
  <b>P</b> : Needs ACK from <b><i>P</i></b>roduct Management</br>
  <b>D</b> : Needs ACK from <b><i>D</i></b>evelopment</br>
  <b>Q</b> : Needs ACK from <b><i>Q</i></b>uality Assurance</br>
  <b>O</b> : Needs ACK from D<b><i>o</i></b>cumentation</br>
  <b>B</b> : Needs ACK from Bugzilla <b><i>B</i></b>ot</br>
  
  <table>
    <% @errata_report_need_acks.each do |bz| %>
      <tr class="<%= cycle('tag_line_odd', 'tag_line_even') %>">
        <td>
        <a href="<%=get_bugzilla_uri%><%= bz[:BZ_ID] %>"><%= bz[:BZ_ID] %></a>
        </td>
        <td><%= bz[:ACKS] %></td>
        <td><%= bz[:SUMMARY] %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

</p>

<p>
  <b>BZs That Have All ACKs:</b>
  <table>
    <% @errata_report_have_acks.each do |bz| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td>
        <a href="<%=get_bugzilla_uri%><%= bz[:BZ_ID] %>"><%= bz[:BZ_ID] %></a>
        </td>
        <td><%= bz[:SUMMARY] %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

</p>

<%= link_to 'Back', issues_path %>

app/views/errata_reports/index.html.erb
<p id="notice"><%= notice %></p>

<h2> Bugzilla Issues in <b>POST</b> state that need ACK(s)</br> </h2>

<p>
<table>
  <tr><i>Number of Issues found: </i><b> <%= @need_acks.count %> </b> &nbsp; &nbsp; </tr>
</table>
</p>

<p>
  <table border="1">
    <tr>
      <th width="10" colspan="1" rowspan="2" scope="col">
        <%= sortable "bug_id", "Bug Id" %>
      </th>
      <th width="10" colspan="1" rowspan="2" scope="col">
        <%= sortable "depends_on_ids", "Depends On" %>
      </th>
      <th width="10" colspan="1" rowspan="2" scope="col">
        <%= sortable "flag_version" %>
      </th>
      <th width="10" colspan="1" rowspan="2" scope="col">
        <%= sortable "commit" %>
      </th>
      <th class="list_line_even" width="100" colspan="3" scope="col">Has ACKs</th>
      <th width="600" colspan="1" rowspan="2" scope="col"> Summary</th>
    </tr>
    <tr>
      <th class="list_line_even" width="60"><%= sortable "pm_ack", "PM" %></th> 
      <th class="list_line_even" width="60"><%= sortable "devel_ack", "Devel" %></th> 
      <th class="list_line_even" width="60"><%= sortable "qa_ack", "QA" %></th> 
    </tr>

    <% @need_acks.each do |bz| %>
      <tr class="<%= cycle('tag_line_odd', 'tag_line_even') %>">
        <td><%= form_tag("/dashboard/view_issue/#{bz.bug_id}", method: "get") do %>
              <%= submit_tag(bz.bug_id) %>
            <% end %>
        </td>
        <td><% ids_list(bz.depends_on_ids).each do |bug_id| %>
              <%= form_tag("/dashboard/view_issue/#{bug_id}", method: "get") do %>
                    <%= submit_tag(bug_id) %>
              <% end
            end %>
        </td>
        <td align="center"> <span class="green_text"><%= flag_versions_string(bz.flag_versions) %></span></td>
        <td><%= list_last_commit(bz) %></td>
        <td align="center"> <span class="green_text"><%= bz.pm_acks %></span></td>
        <td align="center"> <span class="green_text"><%= bz.devel_acks %></span></td>
        <td align="center"> <span class="green_text"><%= bz.qa_acks %></span></td>
        <td><%= bz.summary %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

</p>
<%= link_to 'Back', dashboard_index_path %>

<br>
<hr>
<br>

<p>
  <h2> Bugzilla Issues in <b>POST</b> state that have all the needed ACKs</br> </h2>

  <p>
  <table>
    <tr><i>Number of Issues found: </i><b> <%= @have_acks.count %> </b> &nbsp; &nbsp; </tr>
  </table>
  </p>

  <table border="1">
    <tr>
      <th><%= sortable "bug_id", "BUG ID" %></th>
      <th><%= sortable "depends_on_ids", "Depends On" %></th>
      <th><%= sortable "flag_version" %></th>
      <th><%= sortable "commit" %></th>
      <th> Summary</th>
    </tr>
    <% @have_acks.each do |bz| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td><%= form_tag("/dashboard/view_issue/#{bz.bug_id}", method: "get") do %>
              <%= submit_tag(bz.bug_id) %>
            <% end %>
        </td>
        <td><% ids_list(bz.depends_on_ids).each do |bug_id| %>
              <%= form_tag("/dashboard/view_issue/#{bug_id}", method: "get") do %>
                    <%= submit_tag(bug_id) %>
              <% end
            end %>
        </td>
        <td><%= flag_versions_string(bz.flag_versions) %></td>
        <td><%= list_last_commit(bz) %></td>
        <td><%= bz.summary %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

</p>

<%= link_to 'Back', dashboard_index_path %>

app/views/errata_reports/run.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Report Name:</b>
  <%= @errata_report.name %>
</p>

<p>
  <b>Description:</b>
  <%= @errata_report.description %>
</p>

<p>
  <b>BzQuery Name:</b>
  <%= @errata_report.version %>
</p>

<p>
  <b>BzQuery ID:</b>
  <%= @errata_report.query_id %>
</p>

<p>
  <b>BzQuery Name:</b>
  <%= @errata_report.query_name %>
</p>

<p>
  <b>BzQuery Occurrence Time:</b>
  <%= BzQueryOutput.find_by_id(@errata_report.query_id).updated_at %>
</p>

<p>
  <b>Email Address Devel:</b>
  <%= @errata_report.email_addr_devel_ack %>
</p>

<p>
  <b>Email Address PM:</b>
  <%= @errata_report.email_addr_pm_ack %>
</p>

<p>
  <b>Email Address QA:</b>
  <%= @errata_report.email_addr_qa_ack %>
</p>

<p>
  <b>Send Email To Devel:</b>
  <%= @errata_report.send_email_devel_ack %>
</p>

<p>
  <b>Send Email To PM:</b>
  <%= @errata_report.send_email_pm_ack %>
</p>

<p>
  <b>Send Email To QA:</b>
  <%= @errata_report.send_email_qa_ack %>
</p>

<p>
  <b>BZs That Need ACK(s):</b></br>
  <u><i>Legend:</i></u></br>
  <b>-</b> : Have ACK For This Column</br>
  <b>P</b> : Needs ACK from <b><i>P</i></b>roduct Management</br>
  <b>D</b> : Needs ACK from <b><i>D</i></b>evelopment</br>
  <b>Q</b> : Needs ACK from <b><i>Q</i></b>uality Assurance</br>
  <b>O</b> : Needs ACK from D<b><i>o</i></b>cumentation</br>
  <b>B</b> : Needs ACK from Bugzilla <b><i>B</i></b>ot</br>
  
  <table>
    <% @errata_report_need_acks.each do |bz| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td>
        <a href="<%=get_bugzilla_uri%><%= bz[:BZ_ID] %>"><%= bz[:BZ_ID] %></a>
        </td>
        <td><%= bz[:ACKS] %></td>
        <td><%= bz[:SUMMARY] %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

</p>

<p>
  <b>BZs That Have All ACKs:</b>
  <table>
    <% @errata_report_have_acks.each do |bz| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td>
        <a href="<%=get_bugzilla_uri%><%= bz[:BZ_ID] %>"><%= bz[:BZ_ID] %></a>
        </td>
        <td><%= bz[:SUMMARY] %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

</p>


<%= link_to 'Back', errata_reports_path %>